version: "3.8"
services:
  backend:
    build: ./BrainStation-Backend
    container_name: brainstation_backend
    ports:
      - "3000:3000"
    env_file:
      - ./BrainStation-Backend/.env

  frontend:
    build: ./BrainStation-Frontend
    container_name: brainstation_frontend
    ports:
      - "5173:5173"
    env_file:
      - ./BrainStation-Frontend/.env  

  content_chunking:
    build: ./Content-chunking
    container_name: content_chunking
    ports:
      - "9000:9000"
    env_file:
      - ./Content-chunking/.env

  emotion_detection:
    build: ./Emotion-detection
    container_name: emotion_detection
    ports:
      - "443:443"
    volumes:
      - /etc/ssl/certs/selfsigned.crt:/etc/ssl/certs/selfsigned.crt
      - /etc/ssl/private/selfsigned.key:/etc/ssl/private/selfsigned.key

  exam_prediction:
    build: ./Exam-predictor
    container_name: exam_prediction
    ports:
      - "9002:9002"

  question_generation:
    build: ./Question-generation
    container_name: question_generation
    ports:
      - "9003:9003"

  generate_ontology:
    build: ./Generate-ontology
    container_name: generate_ontology
    ports:
      - "9004:9004"
    env_file:
      - ./Generate-ontology/.env
