version: "3.8"
services:
  backend:
    build: ./BrainStation-Backend
    container_name: brainstation_backend
    ports:
      - "3000:3000"
    env_file:
      - ./BrainStation-Backend/.env

  brainstation_frontend:
    build: ./BrainStation-Frontend
    container_name: brainstation_frontend
    ports:
      - "5173:5173"
    env_file:
      - ./BrainStation-Frontend/.env

  brainstation_admin:
    build: ./BrainStation-Admin
    container_name: brainstation_admin
    ports:
      - "9009:9009"
    env_file:
      - ./BrainStation-Admin/.env

  content_chunking:
    build: ./Content-chunking
    container_name: content_chunking
    ports:
      - "9000:9000"
    env_file:
      - ./Content-chunking/.env

  emotion_detection:
    build: ./Emotion-detection
    container_name: emotion_detection
    ports:
      - "9001:9001"

  exam_prediction:
    build: ./Exam-predictor
    container_name: exam_prediction
    ports:
      - "9002:9002"

  question_generation:
    build: ./Question-generation
    container_name: question_generation
    ports:
      - "9003:9003"

  generate_ontology:
    build: ./Generate-ontology
    container_name: generate_ontology
    ports:
      - "9004:9004"
    env_file:
      - ./Generate-ontology/.env

  adhd_feedback:
    build: ./adhd-level-feedback
    container_name: adhd_feedback
    ports:
      - "9005:9005"
    env_file:
      - ./adhd-level-feedback/.env

  asrs_question_generation:
    build: ./asrs-question-generation
    container_name: asrs_question_generation
    ports:
      - "9006:9006"
    env_file:
      - ./asrs-question-generation/.env

  feedback_predict:
    build: ./feedback_predict
    container_name: feedback_predict
    ports:
      - "9007:9007"
    env_file:
      - ./feedback_predict/.env

  exam_score:
    build: ./exam_score
    container_name: exam_score
    ports:
      - "9008:9008"
